version: '3'
services:
  proxy:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"

  #shell:
    #image: circleci/buildpack-deps 
    #command: bash
    #stdin_open: true
    #tty: true
